# @package _global_

# experiment: "heat_twostreamdiarrttmheat_md_beam5ctc02lp01"
# experiment: "heat_twostreamdiarrttmheat_md_greedy"
experiment: "heat_twostreamdiarhybridloss_md_greedy"

model:
  whisper_model: "openai/whisper-large-v3-turbo"
  reinit_from: "/export/fs06/xhe69/TS-ASR-Whisper/exp/HEAT_ASSIGNkeepchannel_MD_fixeddata/checkpoint-7596/model.safetensors"
  # reinit_from: "/export/fs06/xhe69/TS-ASR-Whisper/exp/HEAT_ASSIGNkeepchannel/checkpoint-4946/model.safetensors"
  # reinit_from: "/export/fs06/xhe69/TS-ASR-Whisper/exp/HEAT_SD_WEIGHTEDSTNO_v2/checkpoint-2281/model.safetensors"

data:
  eval_cutsets: ${oc.env:MANIFEST_DIR}/ami-sdm_test_sc_cutset.jsonl.gz
  dev_cutsets: ${oc.env:MANIFEST_DIR}/ami-sdm_test_sc_cutset.jsonl.gz
  # eval_diar_cutsets: "/export/fs06/xhe69/TS-ASR-Whisper/diar_exp/diarizen_large_twostream_rttmheat/diarized_cutsets/ami-sdm_test_sc_cutset.jsonl.gz"
  # dev_diar_cutsets: "/export/fs06/xhe69/TS-ASR-Whisper/diar_exp/diarizen_large_twostream_rttmheat/diarized_cutsets/ami-sdm_test_sc_cutset.jsonl.gz"
  # eval_diar_cutsets: "/export/fs06/xhe69/TS-ASR-Whisper/diar_exp/diarizen_large_twostream_rttmheat_weightedloss/diarized_cutsets/ami-sdm_test_sc_cutset.jsonl.gz"
  # dev_diar_cutsets: "/export/fs06/xhe69/TS-ASR-Whisper/diar_exp/diarizen_large_twostream_rttmheat_weightedloss/diarized_cutsets/ami-sdm_test_sc_cutset.jsonl.gz"
  eval_diar_cutsets: "/export/fs06/xhe69/TS-ASR-Whisper/diar_exp/diarizen_large_twostreamspeakerchange_sorthybridloss_e16/diarized_cutsets/ami-sdm_test_sc_cutset.jsonl.gz"
  dev_diar_cutsets: "/export/fs06/xhe69/TS-ASR-Whisper/diar_exp/diarizen_large_twostreamspeakerchange_sorthybridloss_e16/diarized_cutsets/ami-sdm_test_sc_cutset.jsonl.gz"
  audio_path_prefix: ${oc.env:AUDIO_PATH_PREFIX}
  audio_path_prefix_replacement: ${oc.env:AUDIO_PATH_PREFIX_REPLACEMENT}
  use_heat_diar: true
  # oracle_heat_assignment_method: "keepchannel"
  diar_type: "twostream"
training:
  decode_only: true
  eval_metrics_list: [ "tcorc_wer" ]
  # generation_num_beams: 5
decoding:
  # decoding_ctc_weight: 0.2
  condition_on_prev: false
  # length_penalty: 0.1
