# @package _global_

# experiment: "heat_oraclediar_sd_speakerchange_beam5ctc02lp01"
# experiment: "libri3mix_heat_keepstreammaxlastsegsend_oraclediar_md_beam5ctc02lp01"
experiment: "sparselibri2mix_heat_oraclediar_sd_keepstream_greedy"

model:
  whisper_model: "openai/whisper-large-v3-turbo"
  # reinit_from: "/export/fs06/xhe69/TS-ASR-Whisper/exp/HEAT_ASSIGNkeepchannel_MD_fixeddata/checkpoint-7596/model.safetensors"
  # reinit_from: "/export/fs06/xhe69/TS-ASR-Whisper/exp/HEAT_ASSIGNkeepchannel/checkpoint-4946/model.safetensors"
  # reinit_from: "/export/fs06/xhe69/TS-ASR-Whisper/exp/HEAT_SD_WEIGHTEDSTNO_v2/checkpoint-2281/model.safetensors"
  # reinit_from: "/export/fs06/xhe69/TS-ASR-Whisper/exp/HEAT_SDAMI_JOINER_v32/checkpoint-6084/model.safetensors"
  reinit_from: "/export/fs06/xhe69/TS-ASR-Whisper/exp/HEAT_MD_WEIGHTEDSTNO_v5/checkpoint-15192/model.safetensors"
  # reinit_from: "/export/fs06/xhe69/TS-ASR-Whisper/exp/HEAT_SD_KEEPSTREAMMAXSEGSTART/checkpoint-2283/model.safetensors"
  # reinit_from: "/export/fs06/xhe69/TS-ASR-Whisper/exp/HEAT_SD_REORDERENCLAVE_v1/checkpoint-1901/model.safetensors"
  
  # reinit_from: "/export/fs06/xhe69/TS-ASR-Whisper/exp/HEAT_ASSIGNspeakerchange_v4/checkpoint-2281/model.safetensors"
  # use_channel_joiner: true
data:
  # eval_cutsets: ${oc.env:MANIFEST_DIR}/ami-sdm_test_sc_cutset.jsonl.gz
  # eval_cutsets: ${oc.env:MANIFEST_DIR}/libri3mix_mix_clean_sc_test_cutset.jsonl.gz
  eval_cutsets: ${oc.env:MANIFEST_DIR}/sparselibrimix_mix_noisy_sparse_3_0.05_sc_test_cutset.jsonl.gz
  audio_path_prefix: ${oc.env:AUDIO_PATH_PREFIX}
  audio_path_prefix_replacement: ${oc.env:AUDIO_PATH_PREFIX_REPLACEMENT}
  use_heat_diar: true
  oracle_heat_assignment_method: "keepchannel_maxlastsegend"
  vad_mask_weights: true
training:
  decode_only: true
  eval_metrics_list: [ "tcorc_wer" ]
  # generation_num_beams: 5
  per_device_eval_batch_size: 4
decoding:
  # decoding_ctc_weight: 0.2
  condition_on_prev: false
  # length_penalty: 0.1
