# @package _global_
defaults:
  - /train/icassp/diarization_conditioning/base

experiment: DICOW_AMI

data:
  train_cutsets: ${oc.env:MANIFEST_DIR}/ami-sdm_train_sc_cutset_30s.jsonl.gz
  dev_cutsets: ${oc.env:MANIFEST_DIR}/ami-sdm_dev_sc_cutset.jsonl.gz
  eval_cutsets: ${oc.env:MANIFEST_DIR}/ami-sdm_test_sc_cutset.jsonl.gz
  
training:
  metric_for_best_model: tcorc_wer
  train_metrics_list: ["tcorc_wer"]
  eval_metrics_list: ["tcorc_wer"]
  eval_delay: 1

model:
  ctc_weight: 0.3