# @package _global_
defaults:
  - /train/icassp/table1_final-models/base

experiment: HEAT_SD_KC-MLSE_REORDERENCLAVE-5-0dot5_VADMASKWEIGHT_v1

data:
  # train_cutsets:
  # - ${oc.env:MANIFEST_DIR}/notsofar_train_sc_cutset_30s.jsonl.gz
  # - ${oc.env:MANIFEST_DIR}/ami-sdm_train_sc_cutset_30s.jsonl.gz
  # - ${oc.env:MANIFEST_DIR}/libri2mix_both_100_train_sc_cutset_30s.jsonl.gz
  # - ${oc.env:MANIFEST_DIR}/libri2mix_both_360_train_sc_cutset_30s.jsonl.gz
  # dataset_weights:
  #   - 3
  #   - 3
  #   - 1
  #   - 1
  train_cutsets: ${oc.env:MANIFEST_DIR}/ami-sdm_train_sc_cutset_30s.jsonl.gz
  dev_cutsets: ${oc.env:MANIFEST_DIR}/ami-sdm_dev_sc_cutset.jsonl.gz
  eval_cutsets: ${oc.env:MANIFEST_DIR}/ami-sdm_test_sc_cutset.jsonl.gz
  use_heat_diar: true
  oracle_heat_assignment_method: "keepchannel_maxlastsegend"
  vad_mask_weights: true
  
training:
  metric_for_best_model: tcorc_wer
  train_metrics_list: ["tcorc_wer"]
  eval_metrics_list: ["tcorc_wer"]
  eval_delay: 1
  # warmup_steps: 200
  # auto_find_batch_size: true
  # overall_batch_size: 8
  # max_grad_norm: 1.0
  # use_amplifiers_only_n_epochs: 0
  # learning_rate: 2e-6
  # target_amp_lr_multiplier: 100.0


# model:
  # ctc_weight: 0.3
  # use_channel_joiner: true
  # prefixes_to_preheat: ['model.encoder.joiner', 'model.encoder.ln']
  # joiner_prefixes: ['model.encoder.additional_layer', 'model.encoder.additional_self_attention_layer', 'model.encoder.target_amplifiers', 'model.encoder.blank_projection', 'model.encoder.modifiers','model.encoder.target_embeddings_proj', 'model.encoder.lm_head', 'model.encoder.subsample_conv1', 'model.encoder.subsample_conv2']
  # reinit_encoder_from: "/export/fs06/xhe69/TS-ASR-Whisper/exp/HEAT_ASSIGNkeepchannel_MD_fixeddata/checkpoint-7596/model.safetensors"
  # reinit_from: '/export/fs06/xhe69/TS-ASR-Whisper/exp/HEAT_MD_JOINER_v13/checkpoint-3798'
  # reinit_encoder_from: ${oc.env:PRETRAINED_CTC_MODELS_PATH}/${model.whisper_model}_ctc-pretrain_libri/model.safetensors
  # reinit_encoder_from: "/export/fs06/xhe69/TS-ASR-Whisper/exp/HEAT_ASSIGNkeepchannel_MD_fixeddata/checkpoint-7596/model.safetensors"

