# @package _global_
defaults:
  - /train/icassp/base

wandb:
  project: tswhisper
model:
  whisper_model: openai/whisper-large-v3-turbo
  reinit_encoder_from: ${oc.env:PRETRAINED_CTC_MODELS_PATH}/${model.whisper_model}_ctc-pretrain_libri/model.safetensors
